### PR TITLE
Update meta.yaml

### PR DESCRIPTION
**Pull request by koaning**
@sugatoray I just updated doubtlab on pypi and figured I should update it here as well. Is this sufficient?

### CODE REVIEW

**Comment by sugatoray** [comment]
@koaning You need to change at least two things, provided, none of the dependency versions changed. The following is based on PyPI.

- version: `0.1.3`
- sha256: `dc791724e0fadf3ec307512db855d9e95c397263e9a9e9090afe74c5cb8d2e3b`

If the dependencies change, then you will need to update the recipe manually.

The sha256 that you merged the PR with, is different from what you see on PyPI. :thinking:

**Review by sugatoray — COMMENTED** [review]
@koaning You need to update the `sha256` and the `version` at least. I see that you have merged with a different `sha256` value (as compared to PyPI). If you were to fix this with the same sha256 as that on PyPI, you would need to create a new PR with the correct sha256 and also bump the build-number by `1` (as this is the second revision for the same version, `v0.1.3`).

```diff
  {% set name = "doubtlab" %}
  {% set version = "0.1.3" %}

  package:
    name: {{ name|lower }}
    version: {{ version }}

  source:
	url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
-   sha256: 18b95efb12012943a9443f1fa585baff1ff231d374b92912877d27908a6abdd4
+   sha256: dc791724e0fadf3ec307512db855d9e95c397263e9a9e9090afe74c5cb8d2e3b

  build:
-   number: 0
+   number: 1
```

**Comment by sugatoray** [comment]
You can get the sha256 either using UI (see below).

### Step-1

Open the specific release files. And click on <kbd>view</kbd> next to the `tar.gz` file.

image

### Step-2

Click on <kbd>copy</kbd> next to the `sha256` value.

image

**Comment by sugatoray** [comment]
`[EDITED]`

After the last PR merge we have this (`v0.1.3`):

```
sha256: 18b95efb12012943a9443f1fa585baff1ff231d374b92912877d27908a6abdd4
```

> This is the same sha256 value you get from Grayskull utility as well.

**Comment by sugatoray** [comment]
@koaning Do you know why this difference in sha256 is happening? I don't know how this impacts the build! 

Possible reason: https://stackoverflow.com/questions/55700453/sha256-different-values-for-same-string

**Comment by koaning** [comment]
It's possible that I added another commit after pushing to pypi. When I spot a spelling mistake in the readme, I usually commit to main directly.

**Comment by sugatoray** [comment]
Sorry, I mistakenly looked at the sha256 value of the wheel file on PyPI. The sha256 on PyPI is the same as that from Grayskull for `v0.1.3`. False alarm!

```
sha256: 18b95efb12012943a9443f1fa585baff1ff231d374b92912877d27908a6abdd4
```

**Pull request closed without merging**
